### ISSUE TITLE
What's going on here? 

### ISSUE THREAD

**Issue by alberto98fx** [kaa2102/Rollbar#3]
<img width="920" alt="image" src="https://github.com/kaa2102/Rollbar/assets/21008855/525c6a61-785f-43ab-b99f-bbaf24666931">
<img width="1061" alt="image" src="https://github.com/kaa2102/Rollbar/assets/21008855/fc5c8069-3fd8-4a02-8d89-467ecf02ab79">
Hey man, 
What's going on here? How did I get your stuff in my personal email associated with a project on Rollbar different from yours?

**Comment by mruhlin** [comment]
My whole team is getting these too, lol.  Please make it stop @kaa2102

**Comment by alberto98fx** [comment]
@mruhlin I'm relieved I'm not the only one!

**Comment by suculent** [comment]
Mee too. What's going on at Rollbar? This is an IDOR security incident and should be reported.

**Comment by nmapx** [comment]
same here, not that hard to google you ;)

**Comment by mruhlin** [comment]
I sent an email to their support before finding this repo.  Not sure if there's better ways to report stuff like that.

Hope they don't come down too hard on you Keith.  Everybody makes mistakes.

**Comment by alberto98fx** [comment]
Me too.
To be completely fair I thought someone stole my account or tokens, it was not the case luckily.
I hope Rollbar will close an eye on this topic, in the end no one was hurt

**Comment by zoiec** [comment]
The org I work for received several of these as well. I emailed rollbar


```
[pytest] testenv - New Error: #2 ZeroDivisionError: division by zero 8:49am MST
[pytest] testenv - New Error: #3 TypeError: unsupported operand type(s) for +: 'int' and 'str' 8:50am MST
```

host is **Keiths-MacBook-Pro.local**

**Comment by alberto98fx** [comment]
Rollbar responded:


> Hi, thanks for reporting this issue. 
> This happened as a result of an internal Rollbar test that resulted in all members of an old newsletter mailing list receiving the email. No customer data has been exposed as a result of this issue. 
> We apologize for the confusion and disruption this morning and thank the many users who wrote in to alert us of the issue.
>  
> Detailed root cause explanation:
> A Rollbar support engineer created a new test project on Rollbar's Rollbar account (named 'Rollbar') and sent a test event into this project. The project was configured to send emails for New Item events to the Everyone team.
> There was a bot member of the Everyone team configured with the email address "[team@rollbar.com](mailto:team@rollbar.com)"
> Earlier this year, a mailing list was created to enable sending the Rollbar monthly newsletter. When the mailing list alias receives valid messages from [rollbar.com](http://rollbar.com/) senders, the message is sent as a newsletter to all members of the mailing list.
> The alias of the mailing list was [team@rollbar.com](mailto:team@rollbar.com)
> As a result, when the New Item message was sent for the test error in the test project this morning, the New Item notification was sent to all members of the mailing list.
>  
> Remediation steps taken:
> We have deleted the old mailing list and no longer use this system for sending newsletters.
> We have removed the above-mentioned bot user from the internal Rollbar Everyone team
>  
> Please let us know if you have any additional questions about this issue.
>  
> Team Rollbar

**Comment by phillram** [comment]
Hi, Phillip from the Rollbar team here. This happened as a result of an internal Rollbar test that resulted in all members of an old newsletter mailing list receiving the email. No customer data has been exposed as a result of this issue. We apologize for the confusion and disruption this morning and thank the many users who wrote in to alert us of the issue.

Detailed root cause explanation:
A Rollbar support engineer created a new test project on Rollbar's Rollbar account (named 'Rollbar') and sent a test event into this project. The project was configured to send emails for New Item events to the Everyone team.
There was a bot member of the Everyone team configured with the email address "[team@rollbar.com](mailto:team@rollbar.com)"
Earlier this year, a mailing list was created to enable sending the Rollbar monthly newsletter. When the mailing list alias receives valid messages from rollbar.com senders, the message is sent as a newsletter to all members of the mailing list.
The alias of the mailing list was [team@rollbar.com](mailto:team@rollbar.com)
As a result, when the New Item message was sent for the test error in the test project this morning, the New Item notification was sent to all members of the mailing list.


Remediation steps taken:
We have deleted the old mailing list and no longer use this system for sending newsletters.
We have removed the above-mentioned bot user from the internal Rollbar Everyone team


Please let us know if you have any additional questions about this issue.

Team Rollbar

**Comment by phillram** [comment]
Oh, looks like @alberto98fx beat me to it 😆

**Comment by alberto98fx** [comment]
@phillram Thank you! :D
